- id: clang-format
  name: clang-format
  entry: clang-format-hook
  description: Formats C, C++, Objective-C, and Java code
  types_or: [c, c++, c#, objective-c, java]
  language: python
- id: clang-tidy
  name: clang-tidy
  entry: clang-tidy-hook
  description: Find warnings/errors in C, C++, and Objective-C code
  types_or: [c, c++, c#, objective-c]
  language: python
